#!/usr/bin/env python3
"""
    grib2json.py

    Python implementation of grib2json.  May not be as robust, and doesn't
    produce the exact same output, but it seems to get the job done

    This is not intended to be a general purpose grib converter.  It is 
    intended to parse grib files retrieved to put weather/ocean data on
    a leaflet map, and to produce output very similar to that generated by 
    the popular and ubiquitous @cambecc/grib2json under those limited 
    constraints.  (see https://github.com/cambecc/grib2json)
"""

import eccodes
import json
import numpy as np
import sys
from datetime import datetime

wanted = [
    "shortName",         # Not in @cambecc/grib2json, but aids humans
    "parameterName",     # Not in @cambecc/grib2json, but aids humans
    "discipline",
    "gribEdition",
    "gribLength",
    "center",
    "subcenter",
    "refTime",
    "significanceOfRT",
    "productStatus",
    "productType",
    "productDefinitionTemplate",
    "parameterCategory",
    "parameterNumber",
    "parameterUnit",
    "genProcessType",
    "forecastTime",
    "surface1Type",
    "surface1Value",
    "surface2Type",
    "surface2Value",
    "gridDefinitionTemplate",
    "numberPoints",
    "shape",
    "gridUnits",
    "resolution",
    "winds",
    "scanMode",
    "nx",
    "ny",
    "basicAngle",
    "lo1",
    "la1",
    "lo2",
    "la2",
    "dx",
    "dy",
]


# This table maps the values grib2json.java output to the 
# actual GRIB2 key name used by ECMWF's eccodes
translate_cambecc_to_eccodes = {
    # discipline (needs no translating)
    "gribEdition": "GRIBEditionNumber",
    "gribLength": "totalLength",
    "center": "centre",
    "subcenter": "subCentre",
    # refTime is a synthetic value.  We generate it ourselves
    "significanceOfRT": "significanceOfReferenceTime",
    "productStatus": "productionStatusOfProcessedData", 
    # productType (needs no translating) FIXME?:  @cambecc says 0, we say 4
    "productDefinitionTemplate": "productDefinitionTemplateNumber",
    # parameterCategory (needs no translating)
    # parameterNumber (needs no translating)
    "parameterUnit": "parameterUnits", 
    "genProcessType":  "typeOfGeneratingProcess",  # Table 4.3
    # forecastTime (needs no translation)
    "surface1Type": "typeOfFirstFixedSurface",     # table 4.5
    "surface1Value": "scaledValueOfFirstFixedSurface",
    "surface2Type": "typeOfSecondFixedSurface",
    "surface2Value": "scaledValueOfSecondFixedSurface",
    "gridDefinitionTemplate": "gridDefinitionTemplateNumber",
    "numberPoints": "numberOfDataPoints",
    "shape": "shapeOfTheEarth",                   # table 3.2
    # gridUnits (WTF?)
    "resolution": "resolutionAndComponentFlags",
    "winds": "uvRelativeToGrid",  # synthetic value: table 3.3 bit 5 == 0
    "scanMode": "scanningMode",
    "nx": "Ni",
    "ny": "Nj",
    "basicAngle": "mBasicAngle",
    "lo1": "longitudeOfFirstGridPointInDegrees",
    "la1": "latitudeOfFirstGridPointInDegrees",
    "lo2": "longitudeOfLastGridPointInDegrees",
    "la2": "latitudeOfLastGridPointInDegrees",
    "dx": "iDirectionIncrementInDegrees",
    "dy": "jDirectionIncrementInDegrees",
}

want_string = [
    "shortName",
    "parameterName",
    "parameterUnit",
    "winds",
]

#
# refTime is a synthetic value which the eccodes library doesn't
# seem to provide.  So provide it ourselves.

def get_refTime(gid):
    try:
        grib_year = eccodes.codes_get(gid, "year")
        grib_month = eccodes.codes_get(gid, "month")
        grib_day = eccodes.codes_get(gid, "day")
        grib_hour = eccodes.codes_get(gid, "hour")
        grib_minute = eccodes.codes_get(gid, "minute")
        grib_second = eccodes.codes_get(gid, "second")

        reftime = datetime.now()
        reftime = reftime.replace(year=grib_year, month=grib_month)
        reftime = reftime.replace(day=grib_day, hour=grib_hour)
        reftime = reftime.replace(minute=grib_minute, second=grib_second)
        reftime = reftime.replace(microsecond=0)
        return reftime.strftime("%Y-%m-%dT%H:%M:%S.000Z")
    except Exception as e:
        print(f"{e} calculating refTime", file=sys.stderr)
        return "unknown"

def run_example(input):
    with open(input, 'rb') as f:
        a = []
        while True:
            gid = eccodes.codes_grib_new_from_file(f)
            if gid is None:
                break

            b = {}
            c = {}
            for key in wanted:      # 'wanted' is @cambecc's keys
                if key == "refTime":
                    value = get_refTime(gid)
                    c[key] = value
                    continue
                if key == "gridUnits":
                    # near as I can tell, there is no key or table
                    # that actually specifies this.  Punt.
                    # Could be that if gDTnumber == 0 (table 3.1) ....
                    c[key] = "degrees"
                    continue;

                translated_key = key
                if key in translate_cambecc_to_eccodes:
                    translated_key = translate_cambecc_to_eccodes[key]

                try:
                    #print(f"trying to get {key}", file=sys.stderr)
                    value = None
                    if key in want_string:  # parameterUnit, wind
                        value = eccodes.codes_get(gid, translated_key)
                        if key == "winds" and value == 0:
                            value = "true"
                    else:
                        # most other keys in @cambecc seem to want integers
                        value = eccodes.codes_get(gid, translated_key, ktype=int)
                    c[key] = value
                except Exception as e:
                    exc_type, exc_obj, tb = sys.exc_info()
                    line_number = tb.tb_lineno
                    print(f"{e} getting value of {key} on line {line_number}", file=sys.stderr)
            b['header'] = c

            # Finally, get "data"
            try:
                data = eccodes.codes_get_array(gid, 'codedValues')
                if isinstance(data, np.ndarray):
                    data = data.tolist()
                    rounded_list = [round(item, 5) for item in data]
                    data = rounded_list 
                b['data'] = data
            except Exception as e:
                print(f"{e} getting data", file=sys.stderr)

            a.append(b)

        try:
            eccodes.codes_release(gid)
        except Exception as e:
            pass
        return a;

if __name__ == "__main__":
    ifile = 'test.grb'
    ofile = sys.stdout
    if (len(sys.argv) == 2):
        ifile = sys.argv[1]
    if (len(sys.argv) == 3):
        ofile = open(sys.argv[2], "w")
    try:
        a = run_example(ifile)
        print(json.dumps(a, indent=2), file=ofile)
    except Exception as e:
        exc_type, exc_obj, tb = sys.exc_info()
        line_number = tb.tb_lineno
        print(f"{e} on line {line_number}", file=sys.stderr)

'''
Help screen from @cambecc's grib2json.  Maybe we could spruce ours up a bit

Usage: grib2json [options] FILE
	[--compact -c] : enable compact Json formatting
	[--data -d] : print GRIB record data
	[--filter.category --fc value] : select records with this numeric category
	[--filter.parameter --fp value] : select records with this numeric parameter
	[--filter.surface --fs value] : select records with this numeric surface type
	[--filter.value --fv value] : select records with this numeric surface value
	[--help -h] : display this help
	[--names -n] : print names of numeric codes
	[--output -o value] : write output to the specified file (default is stdout)
	[--verbose -v] : enable logging to stdout
'''
